language: r
sudo: required
cache: packages
dist: trusty

apt_packages:
  - r-cran-rgdal
  - libproj-dev

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

r_packages:
  - rgeos
  - sf

notifications:
  email:
    on_success: change
    on_failure: change
