language: c

sudo: false

env:
  - R_PKG="$(basename $TRAVIS_REPO_SLUG)"

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-cran-boot
    - r-cran-class
    - r-cran-cluster
    - r-cran-codetools
    - r-cran-foreign
    - r-cran-kernsmooth
    - r-cran-lattice
    - r-cran-mass
    - r-cran-matrix
    - r-cran-mgcv
    - r-cran-nlme
    - r-cran-nnet
    - r-cran-rodbc
    - r-cran-rpart
    - r-cran-spatial
    - r-cran-survival
    - libgdal1-dev
    - libproj-dev

install:
  - "wget -q -O - http://yihui.name/xran/r-config | bash"
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"

cache:
  directories:
  - $HOME/R

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check $R_PKG*.tar.gz --no-manual
  - cd $R_PKG

